import test from 'node:test';
import assert from 'node:assert/strict';
import {CARS,normaliseSave,purchaseCar,selectCar,awardRace} from '../public/dealership-data.mjs';
import {championshipStatus,canEnterRace,recordChampionshipWin,opponentProfile,advanceRace} from '../public/championship-data.mjs';
test('old saves retain credits, cars and tuning with only Starter unlocked',()=>{const s=normaliseSave({credits:42,owned:['starter-1'],selected:'starter-1',tuning:{'starter-1':{engine:2}}});assert.equal(s.credits,42);assert.equal(s.tuning['starter-1'].engine,2);assert.deepEqual(championshipStatus(s).map(c=>c.unlocked),[true,false,false,false,false]);assert.deepEqual(championshipStatus(s).map(c=>c.opponents.length),[5,5,5,5,5])});
test('five distinct wins earn next licence; replays and losses do not inflate progress',()=>{let s=normaliseSave();for(let i=0;i<5;i++){const result=recordChampionshipWin(s,{opponentId:'starter-'+i,playerId:'starter-0',win:true});s=result.save;assert.equal(result.licence,i===4?'Roadster':null);const replay=recordChampionshipWin(s,{opponentId:'starter-'+i,playerId:'starter-0',win:true});assert.equal(replay.newWin,false);assert.equal(replay.licence,null)}assert.equal(s.championship.wins.length,5);assert.equal(championshipStatus(s)[1].unlocked,true);const lost=recordChampionshipWin(s,{opponentId:'starter-0',playerId:'starter-0',win:false});assert.deepEqual(lost.save.championship,s.championship)});
test('locked classes and mismatched cars cannot enter or register wins',()=>{let s=normaliseSave({credits:999999,owned:['roadster-0']});assert.equal(canEnterRace(s,'roadster-1').ok,false);assert.equal(recordChampionshipWin(s,{opponentId:'roadster-1',playerId:'roadster-0',win:true}).newWin,false);s=selectCar(s,'roadster-0').save;assert.equal(canEnterRace(s,'starter-1').ok,false);assert.equal(canEnterRace(s,'missing').ok,false)});
test('all 25 wins unlock in order and award final Champion licence',()=>{let s=normaliseSave({owned:CARS.map(c=>c.id)});let last;for(const cls of championshipStatus(s)){s=selectCar(s,cls.opponents[0].id).save;for(const c of cls.opponents){assert.ok(canEnterRace(s,c.id).ok);last=recordChampionshipWin(s,{opponentId:c.id,playerId:s.selected,win:true});s=last.save}}assert.equal(last.licence,'Champion');assert.equal(s.championship.wins.length,25);assert.ok(championshipStatus(s).every(c=>c.complete));assert.deepEqual(normaliseSave(JSON.parse(JSON.stringify(s))),s)});
test('wins survive garage transactions, rewards and selection changes',()=>{let s=recordChampionshipWin(normaliseSave(),{opponentId:'starter-2',playerId:'starter-0',win:true}).save;s=purchaseCar(s,'starter-1').save;s=awardRace(s,{win:true}).save;assert.deepEqual(s.championship.wins,['starter-2']);assert.equal(s.selected,'starter-1')});
test('malformed or out-of-order progress cannot skip licence requirements',()=>{const s=normaliseSave({championship:{wins:['missing','starter-1','starter-1','super-4','roadster-0']}});assert.deepEqual(s.championship.wins,['starter-1'])});
test('a completed loss grants 375 credits without granting wins or licences',()=>{
 const original=normaliseSave(),reward=awardRace(original,{win:false,perfect:5,launch:'PERFECT'});
 assert.equal(reward.reward,375);assert.equal(reward.save.credits,original.credits+375);
 const progress=recordChampionshipWin(reward.save,{win:false,opponentId:'starter-4',playerId:'starter-0'});
 assert.deepEqual(progress.save.championship.wins,[]);assert.equal(progress.licence,null);assert.equal(championshipStatus(progress.save)[1].unlocked,false);
});
test('each opponent has a distinct fixed pace independent of player upgrades',()=>{assert.equal(new Set(CARS.map(c=>JSON.stringify(opponentProfile(c.id)))).size,25);for(const cls of championshipStatus(normaliseSave())){const p=cls.opponents.map(c=>opponentProfile(c.id));for(let i=1;i<5;i++)assert.ok(p[i].acceleration>p[i-1].acceleration)}});
test('opponent moves and can win while player waits in neutral',()=>{const state={dist:0,cpu:0,time:0};let outcome=null;for(let i=0;i<2000&&outcome===null;i++)outcome=advanceRace(state,.035,0,opponentProfile('starter-0'));assert.equal(outcome,null);assert.ok(Number.isFinite(state.cpuFinishTime));assert.equal(state.dist,0);assert.ok(state.cpu>=402.336)});
test('crossing order within one frame determines winner, not final overshoot',()=>{let s={dist:403,cpu:402.30,time:30};assert.equal(advanceRace(s,.035,402.2,opponentProfile('starter-4')),false);assert.ok(s.cpu>s.dist);s={dist:403,cpu:401,time:30};assert.equal(advanceRace(s,.035,402.3,opponentProfile('starter-4')),true);assert.equal(s.dist,402.336);assert.ok(s.dist>s.cpu)});
