import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {PARTS,buyPart,cleanTune,tunedCar,tickNitro} from '../public/tuning-data.mjs';
import {CARS,getCar,normaliseSave,purchaseCar,sellCar,awardRace} from '../public/dealership-data.mjs';
test('old garages migrate without losing balance, selection or cars',()=>{const s=normaliseSave({credits:77,owned:['starter-1'],selected:'starter-1'});assert.equal(s.credits,77);assert.equal(s.selected,'starter-1');assert.deepEqual(s.tuning,{})});
test('every performance stage improves its promised stats and costs more',()=>{for(const base of CARS)for(const category of ['engine','wheels','turbo']){let previous=tunedCar(base),price=0;for(const part of PARTS[category]){const next=tunedCar(base,{[category]:part.id});assert.ok(next.weight<previous.weight);assert.ok(next.acceleration>previous.acceleration);if(category!=='wheels')assert.ok(next.hp>previous.hp);if(category==='turbo')assert.ok(next.topSpeed>previous.topSpeed);assert.ok(part.price>price);previous=next;price=part.price}}});
test('all colours cost 100 and upgrades never change stock catalogue',()=>{for(const p of PARTS.paint)assert.equal(p.price,100);const c=getCar('starter-0');assert.equal(tunedCar(c).acceleration,1);tunedCar(c,{engine:3,turbo:3,wheels:3});assert.equal(c.hp,150);assert.equal(c.weight,1150)});
test('upgrades charge once and reject downgrades, unknown parts, unowned cars and low balances',()=>{const save=normaliseSave(),r=buyPart(save,'starter-0','engine',2);assert.ok(r.ok);assert.equal(r.save.credits,5500);assert.equal(save.credits,10000);assert.equal(buyPart(r.save,'starter-0','engine',2).ok,false);assert.equal(buyPart(r.save,'starter-0','engine',1).ok,false);assert.equal(buyPart(save,'super-0','engine',1).ok,false);assert.equal(buyPart(save,'starter-0','engine',99).ok,false);assert.equal(buyPart({...save,credits:1},'starter-0','paint','red').ok,false)});
test('per-car upgrades persist through purchases, rewards and JSON reload',()=>{let s=buyPart(normaliseSave(),'starter-0','nitro',1).save;s=purchaseCar(s,'starter-1').save;s=buyPart(s,'starter-1','paint','blue').save;s=awardRace(s,{win:true}).save;const reload=normaliseSave(JSON.parse(JSON.stringify(s)));assert.deepEqual(reload,s);assert.equal(tunedCar(getCar('starter-0'),reload.tuning['starter-0']).nitroSeconds,2);assert.equal(reload.tuning['starter-1'].paint,'blue');assert.equal(reload.tuning['starter-1'].nitro,0)});
test('selling a car removes its upgrades and repurchasing cannot reclaim them free',()=>{let s=purchaseCar(normaliseSave(),'starter-1').save;s=buyPart(s,'starter-1','wheels',1).save;s=sellCar(s,'starter-1').save;assert.equal(s.tuning['starter-1'],undefined);s=purchaseCar(s,'starter-1').save;assert.equal(tunedCar(getCar('starter-1'),s.tuning['starter-1']).acceleration,getCar('starter-1').acceleration)});
test('invalid saved stages and paint are discarded',()=>{assert.deepEqual(cleanTune({engine:99,wheels:-1,paint:'<script>',nitro:Infinity}),cleanTune());const s=normaliseSave({tuning:{'super-0':{engine:3},'starter-0':{engine:3}}});assert.equal(s.tuning['super-0'],undefined);assert.equal(s.tuning['starter-0'].engine,3)});
test('nitro gives exactly two seconds per bottle and no idle consumption',()=>{for(const charge of [2,4]){let remaining=charge,totalBoost=0;for(let i=0;i<500;i++){const r=tickNitro(remaining,.017,true);totalBoost+=(r.multiplier-1)*.017;remaining=r.remaining}assert.equal(remaining,0);assert.ok(Math.abs(totalBoost-charge*.65)<1e-8);assert.equal(tickNitro(charge,60,false).remaining,charge)}});

export function race(){
 let clock=0;
 const elements=new Map(),handlers=new Map();
 const element=()=>({style:{setProperty(k,v){this[k]=v}},classList:{add(){},remove(){},toggle(){},contains(){return false}},innerHTML:'',textContent:'',offsetLeft:90,offsetWidth:300,clientWidth:1280,appendChild(){},after(){},insertBefore(){},setAttribute(){},setPointerCapture(){},querySelector(){return element()}});
 const get=id=>{if(!elements.has(id))elements.set(id,element());return elements.get(id)};
 const on=(name,fn)=>{if(!handlers.has(name))handlers.set(name,[]);handlers.get(name).push(fn)};
 const dispatch=e=>{for(const fn of handlers.get(e.type)||[])fn(e)};
 const context=vm.createContext({document:{head:element(),currentScript:{src:'http://localhost/physics-v2.js'},createElement:element,getElementById:get,querySelector:get,addEventListener:on,dispatchEvent:dispatch},URL,CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail}},state:{},keys:new Set(),raf:0,show(){},showMenu(){},startRace(){},finish(){},shift(){},loop(){},performance:{now:()=>0},requestAnimationFrame:()=>1,cancelAnimationFrame(){},clearTimeout(){},setTimeout(){},addEventListener:on,...Object.fromEntries(['msg','gear','amber','green','rpm','needle','speed','time','pp','cp','cpuCar','playerCar','heroCar','pedal'].map(id=>[id,get(id)]))});
 vm.runInContext(readFileSync(new URL('../public/physics-v2.js',import.meta.url),'utf8'),context);
 dispatch({type:'jd:nitro-model',detail:{tick:tickNitro}});
 function vehicle(seconds=2){dispatch({type:'jd:vehicle',detail:{acceleration:1,topSpeed:120,nitroSeconds:seconds}})}
 vehicle();context.startRace();Object.assign(context.state,{phase:'GO',gear:1,speed:16,rpm:3500,time:1,launch:'PERFECT',gas:true,last:1000});
 context.performance.now=()=>clock;
 return {context,dispatch,vehicle,step:t=>{clock=t;context.loop(t)}};
}
test('actual race loop applies boost to acceleration and spends only simulation time',()=>{const ordinary=race(),boosted=race();boosted.context.keys.add('KeyN');ordinary.step(1030);boosted.step(1030);assert.ok(boosted.context.state.speed>ordinary.context.state.speed);assert.ok(Math.abs(boosted.context.state.nitroRemaining-1.97)<1e-8);assert.equal(ordinary.context.state.nitroRemaining,2)});
test('actual race loop does not burn nitro in neutral, pre-start, or off throttle',()=>{for(const change of [{gear:0},{phase:'READY'},{gas:false}]){const r=race();Object.assign(r.context.state,change);r.context.keys.add('KeyN');r.step(1030);assert.equal(r.context.state.nitroRemaining,2)}});
test('new races refill bottles; switching to a car with none removes nitro',()=>{const r=race();r.context.state.nitroRemaining=0;r.context.startRace();assert.equal(r.context.state.nitroRemaining,2);r.vehicle(4);assert.equal(r.context.state.nitroRemaining,4);r.vehicle(0);assert.equal(r.context.state.nitroRemaining,0)});
test('held nitro cannot create unlimited fuel and releasing stops use',()=>{const r=race();r.context.keys.add('KeyN');for(let i=1;i<100;i++)r.step(1000+i*30);assert.equal(r.context.state.nitroRemaining,0);r.context.startRace();Object.assign(r.context.state,{phase:'GO',gear:1,speed:16,gas:true,last:5000});r.context.keys.delete('KeyN');r.step(5030);assert.equal(r.context.state.nitroRemaining,2)});
